services:
  postfix:
    image: juanluisbaptiste/postfix:latest
    container_name: smtp-server
    hostname: mail.203.18.50.4.nip.io
    restart: unless-stopped
    ports:
      - "25:25"
    environment:
      - SMTP_SERVER=smtp.nvidia.com
      - SMTP_PORT=25
      - SMTP_NETWORKS=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
    volumes:
      - mail_data:/var/mail

volumes:
  mail_data: