services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: notifyhub-postgres
    environment:
      POSTGRES_DB: notifyhublite
      POSTGRES_USER: notifyhub
      POSTGRES_PASSWORD: secure-password-123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  # SMTP Server (Postfix + NVIDIA relay)
  postfix:
    image: juanluisbaptiste/postfix:latest
    container_name: smtp-server
    hostname: mail.${SERVER_IP:-203.18.50.4}.${DOMAIN_SUFFIX:-nip.io}
    restart: unless-stopped
    ports:
      - "25:25"
    environment:
      - SMTP_SERVER=${SMTP_SERVER:-smtp.nvidia.com}
      - SMTP_PORT=${SMTP_PORT:-25}
      - SMTP_NETWORKS=${SMTP_NETWORKS:-10.0.0.0/8,172.16.0.0/12,192.168.0.0/16}
    volumes:
      - mail_data:/var/mail

volumes:
  postgres_data:
  mail_data: