apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "notifyhub-lite.fullname" . }}-config
  labels:
    {{- include "notifyhub-lite.labels" . | nindent 4 }}
data:
  NOTIFYHUB_SERVER_IP: {{ .Values.config.serverIp | quote }}
  NOTIFYHUB_DOMAIN_SUFFIX: {{ .Values.config.domainSuffix | quote }}
  NOTIFYHUB_DEBUG: {{ .Values.config.debug | quote }}
  NOTIFYHUB_SMTP_HOST: {{ include "notifyhub-lite.smtpHost" . | quote }}
  NOTIFYHUB_SMTP_PORT: {{ .Values.smtp.port | quote }}
  NOTIFYHUB_SMTP_USE_TLS: {{ .Values.smtp.useTls | quote }}
  NOTIFYHUB_SMTP_FROM_NAME: {{ .Values.smtp.fromName | quote }}
  {{- if .Values.smtp.fromEmail }}
  NOTIFYHUB_SMTP_FROM_EMAIL: {{ .Values.smtp.fromEmail | quote }}
  {{- end }}
  NOTIFYHUB_DATABASE_URL: {{ include "notifyhub-lite.databaseUrl" . | quote }}
