apiVersion: v1
kind: Secret
metadata:
  name: {{ include "notifyhub-lite.fullname" . }}-secret
  labels:
    {{- include "notifyhub-lite.labels" . | nindent 4 }}
type: Opaque
data:
  NOTIFYHUB_API_KEY: {{ .Values.config.apiKey | b64enc }}
  {{- if .Values.smtp.username }}
  NOTIFYHUB_SMTP_USERNAME: {{ .Values.smtp.username | b64enc }}
  {{- end }}
  {{- if .Values.smtp.password }}
  NOTIFYHUB_SMTP_PASSWORD: {{ .Values.smtp.password | b64enc }}
  {{- end }}
